# Generated by Django 6.0.6 on 2026-06-11 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0004_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='category',
            field=models.CharField(choices=[('Forest', 'Forest'), ('Mountain', 'Mountain'), ('Temple', 'Temple'), ('Beach', 'Beach'), ('Waterfall', 'Waterfall'), ('Historical', 'Historical'), ('Food', 'Food Destination')], default='Forest', max_length=50),
        ),
    ]
