# Generated by Django 6.0.6 on 2026-06-15 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0007_placesuggestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='placesuggestion',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20),
        ),
    ]
