# Generated by Django 6.0.6 on 2026-06-17 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0008_placesuggestion_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='district',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='place',
            name='taluk',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
